### ISSUE TITLE
Integration with network events

### ISSUE THREAD

**Issue by NDolensek** [open-ephys-plugins/online-psth#1]
This plugin looks great! Is there a way to integrate it with the network events plugin and align to e.g. strings sent over the network?

**Comment by jsiegle** [comment]
Yeah, that is actually quite easy! As of GUI version 0.6.0, the [Network Events](https://open-ephys.github.io/gui-docs/User-Manual/Plugins/Network-Events.html) plugin is a Filter that adds TTL events to all data streams that pass through it. So you can associate trial types with up to 256 TTL event lines, and trigger the Online PSTH using a command like this:

`TTL 10 1` ("on" event on line 10)

Note that this is only guaranteed to be temporally accurate within a few ms, whereas hardware TTL events will be accurate to within one sample.

**Comment by NDolensek** [comment]
That's awesome, thanks! Is there a way to access these 256 TTL lines from the online PSTH plugin where the dropdown menu offer only lines 1-16?

**Comment by jsiegle** [comment]
Yeah, you'd just have to change the max value on [this line](https://github.com/open-ephys-plugins/online-psth/blob/245c1636d413097a66271378c3254dc753d532de/Source/OnlinePSTH.cpp#L55) to 256 instead of 16. We can help you with this if necessary.

However, each plugin instance only aligns events to a single TTL line, so you'd need a separate instance for each condition. If you have more than ~10 conditions you need to align to, we would need to rethink the plugin design a bit, for example to allow multiple conditions to be overlaid.

**Comment by NDolensek** [comment]
Thanks, I'll see if I can get this to work for our purposes. A PSTH plugin with overlays does sound great, though (and was functional once https://open-ephys.org/blog/2014/7/9/first-recording-in-nhp-real-time-analysis).

Thank you for your help!
